### ISSUE TITLE
无法加载数据集

### ISSUE THREAD

**Issue by ThinkerWen** [kevwan/chatbot#6]
您好，我不知道是什么原因，看起来无法正常读取yaml数据集。不知道是否是我的使用方式有问题？
ai.yaml 是[chatterbot-corpus](https://github.com/gunthercox/chatterbot-corpus/blob/master/chatterbot_corpus/data/chinese/ai.yml)的。在Mac上和Windows上的使用效果是一样的，都是这样无法读取。

```
D:\VsCode\Go\chatbot\cli\train>go run train.go -i ai.yaml
Loading corpora...
Creating Q/A mappings...
Building indexes...
Elapsed: 3.0005ms

D:\VsCode\Go\chatbot\cli\train>ls

ai.yaml  corpus.gob  train.go

D:\VsCode\Go\chatbot\cli\train>cd ../ask

D:\VsCode\Go\chatbot\cli\ask>go run ask.go -c D:/VsCode/Go/chatbot/cli/train/corpus.gob
Q: 什么是ai
No answer!
Q: hello
No answer!
Q: 你好
No answer!
Q: No answer!
Q: exit status 0xc000013a

D:\VsCode\Go\chatbot\cli\ask>cd ../train

D:\VsCode\Go\chatbot\cli\train>du -sh *
8.0K    ai.yaml
1.0K    corpus.gob
4.0K    train.go
```
![On Windows CMD](https://s2.loli.net/2022/08/27/zJSXmpqCvGbDLM3.png)

**Comment by kevwan** [comment]
路径问题？你调一下吧，看这个文件能否读取到

**Comment by svirmi** [comment]
Have the very same issue

**Comment by svirmi** [comment]
@Raptor-wxw , try to type just hi, I had same result with hello etc. but hi worked and means all the code works
